---
apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: com.github.pozo/spring-boot-jib
      jib:
        type: gradle
  local:
    push: false
test:
  - image: com.github.pozo/spring-boot-jib
    structureTests:
      - ./structure-test/*
deploy:
  helm:
    releases:
      - name: spring-boot-jib
        chartPath: helm
        values:
          image.repository: com.github.pozo/spring-boot-jib
        setValues:
          image.tag: ""
