---
replicaCount: 1

image:
  repository: com.github.pozo/spring-boot-jib
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: "spring-boot-jib"

service:
  type: LoadBalancer
  port: 8080
  containerPort: 55000

ingress:
  enabled: true
  hosts:
    - host: spring-boot-jib.minikube
      paths:
        - /

container:
  ports:
    - name: http
      containerPort: 55000
      protocol: TCP
    - name: debug
      containerPort: 5005
      protocol: TCP

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}
